### ISSUE TITLE
cleanupsyncs - IndexError: list index out of range

### ISSUE THREAD

**Issue by bjester** [learningequality/morango#183]
```
ERROR 2022-08-19 14:46:31,145 kolibri.core.tasks.worker Job 2619b37de22a4aed893176fcc1df2663 raised an exception: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\kolibri\core\tasks\worker.py", line 61, in handle_finished_future
    result = future.result()
  File "c:\python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\tasks\job.py", line 117, in execute_job
    result = func(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\public\utils.py", line 456, in soud_sync_cleanup
    call_command("cleanupsyncs", ids=clean_up_ids, expiration=0)
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\management\__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "c:\python36\lib\site-packages\kolibri\dist\morango\management\commands\cleanupsyncs.py", line 55, in handle
    transfer_session = transfer_sessions[0]
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by bjester** [comment]
I believe this was fixed with the referenced PR
