### ISSUE TITLE
Issue with historic migrations on SQLite < 3.26 with Django 3.2

### ISSUE THREAD

**Issue by rtibbles** [learningequality/morango#224]
Issue running old migrations under Django 3.2 on SQLite < 3.26

```Running migrations:
  Applying morango.0003_auto_20170519_0543...Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 189, in invoke
    initialize(**get_initialize_params())
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 342, in initialize
    update(version, kolibri.__version__)
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 396, in update
    _migrate_databases()
  File "/usr/lib/python3/dist-packages/kolibri/utils/main.py", line 109, in _migrate_databases
    call_command("migrate", interactive=False, database=database)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/commands/migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/migrations/operations/fields.py", line 353, in database_forwards
    to_model._meta.get_field(self.new_name),
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/schema.py", line 115, in alter_field
    ) % (model._meta.db_table, old_field_name))
django.db.utils.NotSupportedError: Renaming the 'morango_scopedefinition'.'scope_id' column while in a transaction is not supported on SQLite &lt; 3.26 because it would break referential integrity. Try adding `atomic = False` to the Migration class.```


[Slack Message](https://learningequality.slack.com/archives/C42EFMC3E/p1718820202793909?thread_ts=1718820202.793909&cid=C42EFMC3E)

Suggested course of action is to squash the migrations so we can just skip this on new installs.

**Comment by pcenov** [comment]
@rtibbles this is preventing me from testing freely new builds on Windows - is there anything that can be done, or we need this issue sorted out first?
