### ISSUE TITLE
Error during session finalization when pushing a large amount of data to KDP

### ISSUE THREAD

**Issue by jamalex** [learningequality/morango#93]
```
INFO     Sent 149500/149834 records
INFO     Sent 149834/149834 records
INFO     Completed push of data
INFO     Closing transfer session
Traceback (most recent call last):
  File "/usr/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri==0.13.2b1', 'console_scripts', 'kolibri')()
  File "/usr/lib/python3/dist-packages/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 243, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/usr/lib/python3/dist-packages/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 641, in manage
    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 102, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/commands/sync.py", line 166, in handle_async
    sync_client.initiate_push(Filter(dataset_id))
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 423, in initiate_push
    self._close_transfer_session()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 591, in _close_transfer_session
    self.sync_connection._close_transfer_session(self.current_transfer_session)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 346, in _close_transfer_session
    self.urlresolve(api_urls.TRANSFERSESSION, lookup=transfer_session.id)
  File "/usr/lib/python3/dist-packages/kolibri/dist/requests/sessions.py", line 615, in delete
    return self.request('DELETE', url, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/session.py", line 21, in request
    logger.error("{} Reason: {}".format(str(httpErr), httpErr.response.json()))
  File "/usr/lib/python3/dist-packages/kolibri/dist/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jamalex** [comment]
This has been resolved.
